version: "3"
services:
  selenium-hub:
   image: selenium/hub
   environment:
   - SE_ENABLE_TRACING=false
   ports: 
   - '4442-4444:4442-4444'
   networks:
   - grid
  
  node-chrome:
   image: selenium/node-chrome
   environment:
   - SE_EVENT_BUS_HOST=selenium-hub
   - SE_EVENT_BUS_PUBLISH_PORT=4442
   - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   - SE_NODE_MAX_SESSIONS=5
   - SE_ENABLE_TRACING=false
   networks: 
   - grid  
   
  node-firefox:
   image: selenium/node-firefox
   environment:
   - SE_EVENT_BUS_HOST=selenium-hub
   - SE_EVENT_BUS_PUBLISH_PORT=4442
   - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   - SE_NODE_MAX_SESSIONS=5
   - SE_ENABLE_TRACING=false
   networks: 
   - grid     
   
networks:
 grid:
  driver: bridge  